server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://18.217.24.174:30001/contiq?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Bootcamp@127!

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost

  flyway:
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    mixed: true
