server:
  port: 9003
  tomcat:
    max-http-form-post-size: 10MB

spring:
  application:
    name: FILE-SERVICE
  datasource:
    url: jdbc:mysql://18.217.24.174:30001/contiq?serverTimezone=UTC
    username: root
    password: Bootcamp@127!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost

  flyway:
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    mixed: true

elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: https://elasticbc127.spcluster.tk/
  host: elasticbc127.spcluster.tk
  port: 443
  username: elastic
  password: elastic@bc127
  truststore:
    path: /home/harshD/Videos/truststore.jks
    password: bootcamp127
